version: "3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports: 
      - "9200:9200"
      - "9300:9300"
    volumes:
      - ./volumes/es:/usr/share/elasticsearch/data
    environment:
      - "discovery.type=single-node"      
      - "xpack.security.enabled=false"
      - "xpack.monitoring.enabled=false"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
      - "ES_JAVA_OPTS=-Xms3g -Xmx3g"
    ulimits:
      nproc: 3000
      nofile: 65536
      memlock: -1
    deploy:
      resources:
        limits:
          memory: 2g
  kibana:
    image: docker.elastic.co/kibana/kibana:6.2.3
    ports:
      - "5601:5601"
    environment:
     - "xpack.security.enabled=false"
     - "xpack.monitoring.enabled=false"  